### ISSUE TITLE
wrapup page should rely on actual results of deploy

### ISSUE THREAD

**Issue by asmorodskyi** [SUSE-Enceladus/blue-horizon#83]
After deploy actually fail with error you still see same page which recommends you how to proceed with working cluster. 

Not sure what would be expected behavior here . I see two main possibilities :
1. Not allow user to switch to wrapup page at all 
2. Have second version of this page saying something "Sorry something went wrong try to find solution here or there "

**Comment by bear454** [comment]
The terraform deployments we're doing are complex, and there are a lot of moving parts and external dependencies... that is to say, sometimes it will fail, regardless of the code.

In this case, though, it can be very useful to still be able to download the result bundle. Terraform-savvy folks will be able to  re-apply, and possibly rescue their cluster. Support may at some point wan the logs, in order to diagnose reported bugs.

**Comment by bear454** [comment]
This is related to #103 .
