### ISSUE TITLE
Concurrent logins are not supported 

### ISSUE THREAD

**Issue by asmorodskyi** [SUSE-Enceladus/blue-horizon#84]
1. Proceed through all steps till Deploy page 
2. Start Deploy proceed
3. While deploy is running start second browser instance and login 
4. In second browser instance try to navigate to Plan page 
==> despite on-going "terraform apply" , navigation to Plan page will trigger "terraform plan" which would ruin on-going "terraform apply"

Expected: there could be few possible solutions : 
1. Block any attempts to login of second user 
2. Allow more than one login but second logins happening in read-only mode 
3. Smart handling of concurrent navigation of two ( or more ) user between phases

**Comment by rjschwei** [comment]
Concurrent logins should be blocked, IMHO

**Comment by bear454** [comment]
#94 will prevent another user from unintentionally stomping on your session, but it's not too rigid, as I don't want a user to have to start another VM, just because they decided to switch browsers.

This doesn't help at all, though, with a user opening multiple tabs in the same browser, as they would share the same session. I'm working on some locking controls during long-running operations to mitigate that as well.
